# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

anchors:
  main-filter: &main-filter
    branches:
      only: main
  pr-filter: &pr-filter
    branches:
      only: /^feature\/.*/
# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/configuration-reference/#jobs
jobs:
  pre-build:
    docker:
      - image: cimg/node:21.4.0
    steps:
      - checkout
      - run:
          name: Update yarn
          command: yarn
      - run:
          name: Run Jest tests
          command: yarn test
  build:
    docker:
      - image: cimg/node:21.4.0
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "yarn.lock" }}
            - v1-dependencies-
      - run:
          name: Update yarn
          command: yarn install
      - save_cache:
          key: v1-dependencies-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules
            - ./.next/cache
      - run:
          name: Run Jest tests
          command: yarn test
      - run:
          name: Build project
          command: yarn build
# Orchestrate jobs using workflows
# See: https://circleci.com/docs/configuration-reference/#workflows
workflows:
  pr:
    jobs:
      - pre-build:
          filters: *pr-filter
  main:
    jobs:
      - build:
          filters: *main-filter
